version: '3.9'

services:
  fgta4_framework:
    container_name: fgta4_framework
    image: webserver_8_1
    hostname: fgta4_framework
    ports:
      - 8003:80
    networks:
      - devnetwork 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DEBUG=true
    volumes:
      - ./docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./../:/var/www/html:consistent
      - ./../localsetting/config.php:/var/www/html/public/config.php
      - ./../localsetting/database:/var/www/html/core/database
      - ./../../retail:/var/www/html/apps/retail
      - ./../../media:/var/www/html/apps/media
      - ./../../hrms:/var/www/html/apps/hrms
      - ./../../crm:/var/www/html/apps/crm
      - ./../../ent:/var/www/html/apps/ent
      - ./../../finact:/var/www/html/apps/finact
    working_dir: /var/www/html

networks:
  devnetwork:
    name: devnetwork
    external: true




