version: '3.9'

services:
  fgta4framework:
    container_name: fgta4framework
    image: webserver_8_1
    hostname: fgta4framework
    ports:
      - 8001:80
    networks:
      - devnetwork 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DEBUG=true
    volumes:
      - ./../:/var/www/html:consistent
    working_dir: /var/www/html

networks:
  devnetwork:
    name: devnetwork
    external: true




