version: '3.9'

services:
  fgta4_framework:
    container_name: fgta4_framework
    image: webserver_8_1
    hostname: fgta4_framework
    ports:
      - 8003:80
    networks:
      - devnetwork 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DEBUG=true
    volumes:
      - ./docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./../:/var/www/html:consistent
      - ./../../finact:/var/www/html/apps/finact
    working_dir: /var/www/html

networks:
  devnetwork:
    name: devnetwork
    external: true




